
project_id = "mrueqpffzauvdxmuwhfa"

[global.env]
PAYPAL_CLIENT_ID = "ASSEeQ2EOkXAmv_QgbwkIXiY_Tg1TPjqXJ71Ox2fy"
PAYPAL_SECRET_KEY = "EEx0adocT7_PR3S6VXCQS1xC6by5UO6OuYIkxeYh"
PAYPAL_WEBHOOK_ID = "8J255804D40512200"
RESEND_API_KEY = "env(RESEND_API_KEY)"
