
project_id = "mrueqpffzauvdxmuwhfa"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[functions.admin-panel-data]
verify_jwt = true

[functions.confirm-signup]
verify_jwt = false

[functions.create-customer-portal-session]
verify_jwt = true

[functions.create-stripe-checkout]
verify_jwt = true

[functions.create-user-admin]
verify_jwt = true

[functions.handle-paypal-webhook]
verify_jwt = false

[functions.handle-subscription-redirect]
verify_jwt = true

[functions.password-reset]
verify_jwt = false

[functions.process-renewals]
verify_jwt = false

[functions.send-booking-approval-email]
verify_jwt = false

[functions.send-booking-request-notification]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-event-reminder-email]
verify_jwt = false

[functions.send-task-reminder-email]
verify_jwt = false

[functions.stripe-checkout-webhook]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.sync-stripe-subscription]
verify_jwt = true

[functions.test-debug]
verify_jwt = false

[functions.test-resend-email]
verify_jwt = false

[functions.validate-datetime]
verify_jwt = true

[functions.verify-paypal-payment]
verify_jwt = false

[functions.verify-stripe-subscription]
verify_jwt = true
