
project_id = "mrueqpffzauvdxmuwhfa"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[functions]
[functions.create-storage-policy]
verify_jwt = true
