
project_id = "mrueqpffzauvdxmuwhfa"

[api]
# Disable schema caching during development
schemas_cache_enabled = false
schemas_cache_max_age = 0

[functions.send-confirmation-email]
# Remove auth verification for email sending (required for registration)
verify_jwt = false
