
project_id = "mrueqpffzauvdxmuwhfa"

[api]
# Port to use for the API URL
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
# Port to use for the local DB URL
port = 54322

[studio]
# Port to use for Supabase Studio
port = 54323

# Email testing server. Emails sent with the local dev setup are not actually sent - the
# mail server will catch them and make them available to view.
[inbucket]
# Port to use for the email testing server web interface
port = 54324

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB")
file_size_limit = "50MiB"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000", "http://localhost:5173", "http://127.0.0.1:5173"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

[functions]
# Port to use for Functions server
port = 54321

# Modify the configuration for the stripe-webhook function to be public
[functions.stripe-webhook]
verify_jwt = false

# Make the PayPal webhook public
[functions.paypal-webhook]
verify_jwt = false

# Make verify-stripe-subscription public to ensure it works even without JWT
[functions.verify-stripe-subscription]
verify_jwt = false
