
# This file controls the configuration for the Supabase CLI's
# functions commands.
project_id = "mrueqpffzauvdxmuwhfa"

[functions]
[functions.stripe-webhook]
verify_jwt = false

[functions.verify-stripe-subscription]
verify_jwt = false

