
# A string used to distinguish different Supabase projects on the same host. Defaults to the project ID.
project_id = "mrueqpffzauvdxmuwhfa"

# The port to expose the Supabase services on. Defaults to 54321.
# port = 54321

[api]
# Port to use for the API URL.
# port = 54321
# Extra schemas to expose in your API. Defaults to ["public", "storage", "graphql_public"].
# exposed_schemas = ["public", "storage", "graphql_public"]

[db]
# Port to use for the local database URL.
# port = 54322

# The database major version to use. This has to be the same as your remote database's.
# major_version = 15

[functions]
[functions.stripe-webhook]
verify_jwt = false

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
# file_size_limit = "50MiB"
