
project_id = "mrueqpffzauvdxmuwhfa"

[functions.send-booking-request-notification]
verify_jwt = false

[functions.send-booking-approval-email]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.handle-paypal-webhook]
verify_jwt = false

[functions.handle-subscription-redirect]
verify_jwt = false

[functions.process-renewals]
verify_jwt = false

[functions.verify-paypal-payment]
verify_jwt = false

[functions.confirm-signup]
verify_jwt = false

[functions.test-resend-email]
verify_jwt = false

[functions.create-user-admin]
verify_jwt = false

[functions.password-reset]
verify_jwt = false

[global.env]
PAYPAL_CLIENT_ID = "env(PAYPAL_CLIENT_ID)"
PAYPAL_SECRET_KEY = "env(PAYPAL_SECRET_KEY)"
PAYPAL_WEBHOOK_ID = "env(PAYPAL_WEBHOOK_ID)"
RESEND_API_KEY = "env(RESEND_API_KEY)"
SUPABASE_ANON_KEY = "env(SUPABASE_ANON_KEY)"
SUPABASE_SERVICE_ROLE_KEY = "env(SUPABASE_SERVICE_ROLE_KEY)"
