
project_id = "mrueqpffzauvdxmuwhfa"

[functions.send-booking-request-notification]
verify_jwt = false

[functions.send-booking-approval-email]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.handle-paypal-webhook]
verify_jwt = false

[functions.handle-subscription-redirect]
verify_jwt = false

[functions.process-renewals]
verify_jwt = false

[functions.verify-paypal-payment]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false
