
project_id = "mrueqpffzauvdxmuwhfa"

[global.env]
PAYPAL_CLIENT_ID = "env(PAYPAL_CLIENT_ID)"
PAYPAL_SECRET_KEY = "env(PAYPAL_SECRET_KEY)"
PAYPAL_WEBHOOK_ID = "env(PAYPAL_WEBHOOK_ID)"
RESEND_API_KEY = "env(RESEND_API_KEY)"
SUPABASE_ANON_KEY = "env(SUPABASE_ANON_KEY)"
SUPABASE_SERVICE_ROLE_KEY = "env(SUPABASE_SERVICE_ROLE_KEY)"
