project_id = "mrueqpffzauvdxmuwhfa"

# The port to expose the Supabase services on. Defaults to 54321.
# port = 54321

[api]
# Port to use for the API URL.
# port = 54321
# Extra schemas to expose in your API. Defaults to ["public", "storage", "graphql_public"].
# exposed_schemas = ["public", "storage", "graphql_public"]

[db]
# Port to use for the local database URL.
# port = 54322

# The database major version to use. This has to be the same as your remote database's.
# major_version = 15

[functions]
[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-checkout-webhook]
verify_jwt = false

[functions.create-stripe-checkout]
verify_jwt = true

[functions.verify-stripe-subscription]
verify_jwt = false

[functions.sync-stripe-subscription]
verify_jwt = true

[functions.send-booking-approval-email]
verify_jwt = false

[functions.send-task-reminder-email]
verify_jwt = false

[functions.send-custom-reminder-email]
verify_jwt = false

[functions.send-direct-email]
verify_jwt = false

[functions.send-event-reminder-email]
verify_jwt = false

[functions.process-reminders]
verify_jwt = false

[functions.admin-delete-sub-users]
verify_jwt = true

[functions.admin-change-user-plan]
verify_jwt = true

[functions.send-comment-email]
verify_jwt = false

[functions.ai-chat]
verify_jwt = true

[functions.generate-excel-report]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = true

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
# file_size_limit = "50MiB"
