-- Drop ALL existing storage policies to start fresh
DROP POLICY IF EXISTS "Allow customer attachments upload" ON storage.objects;
DROP POLICY IF EXISTS "Allow customer attachments view" ON storage.objects;
DROP POLICY IF EXISTS "Allow customer attachments update" ON storage.objects;
DROP POLICY IF EXISTS "Allow customer attachments delete" ON storage.objects;
DROP POLICY IF EXISTS "Allow event attachments upload" ON storage.objects;
DROP POLICY IF EXISTS "Allow event attachments view" ON storage.objects;
DROP POLICY IF EXISTS "Allow event attachments update" ON storage.objects;
DROP POLICY IF EXISTS "Allow event attachments delete" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users general storage" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated uploads" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users to delete booking files" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users to delete customer files" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users to delete event files" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users to delete from booking_attachments" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users to delete from customer_attachments" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users to delete from event_attachments" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users to delete from note_attachments" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users to delete task files" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users to manage general storage" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users to upload booking files" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users to upload customer files" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users to upload event files" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users to upload files" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users to upload task files" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users to upload to customer_attachments" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users to upload to event_attachments" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users to upload to note_attachments" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users to view booking files" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users to view customer files" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users to view event files" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users to view task files" ON storage.objects;
DROP POLICY IF EXISTS "Give users access to own folder 1oj01fe_0" ON storage.objects;
DROP POLICY IF EXISTS "Give users access to own folder 1oj01fe_1" ON storage.objects;
DROP POLICY IF EXISTS "Give users access to own folder 1oj01fe_2" ON storage.objects;
DROP POLICY IF EXISTS "Give users access to own folder 1oj01fe_3" ON storage.objects;